### ISSUE TITLE
MacOS use VirtualHere Input as Keyboard and mouse

### ISSUE THREAD

**Issue by xXBlackBulletXx** [HelloThisIsFlo/Deckpad#11]
I tried to use my SteamDeck on my Macbook Pro M1 Pro, without any results. I guess is something related to the OS because can't recognize as controller input but i would to ask to someone if someone find a workaround to use SD as controller on MacOS. I'll put my VirtualHere System Messages just in case to understand what's going on.
<img width="550" alt="Screenshot 2023-10-17 at 16 18 42" src="https://github.com/HelloThisIsFlo/Deckpad/assets/18627978/b36b2a6a-c6ce-496a-8c61-a5740aae7da0">

**Comment by HelloThisIsFlo** [comment]
It looks like it failed to connect to the Steam Deck: `could not connect to steamdeck.local.:7575`. Not sure what could be causing this 🤔

**Comment by HelloThisIsFlo** [comment]
This is inactive so I'm closing it
